#!/usr/bin/env python3
"""Integration tests for rssani gRPC interface.

Starts the rssani binary, waits for the gRPC server on port 50051,
runs tests against every RPC method, then shuts down.

Usage: python3 test_grpc.py [path/to/rssani]
"""

import sys
import os
import time
import signal
import subprocess
import unittest
import grpc

# Generated by grpc_tools.protoc in the build step
import rssani_pb2
import rssani_pb2_grpc

RSSANI_BIN = sys.argv.pop(1) if len(sys.argv) > 1 else "./build/rssani"
GRPC_ADDR = "localhost:50051"
PROC = None


def setUpModule():
    global PROC
    env = os.environ.copy()
    env["XDG_CONFIG_HOME"] = "/tmp/rssani_test_config"
    os.makedirs(env["XDG_CONFIG_HOME"] + "/Selu", exist_ok=True)
    # Minimal config so rssani doesn't exit on missing values
    with open(env["XDG_CONFIG_HOME"] + "/Selu/rssani.conf", "w") as f:
        f.write("[principal]\npath=/tmp/rssani_test_torrents\ntimer=9999\n")
    os.makedirs("/tmp/rssani_test_torrents", exist_ok=True)
    PROC = subprocess.Popen(
        [RSSANI_BIN],
        env=env,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    # Wait for gRPC server to be ready
    for _ in range(30):
        try:
            with grpc.insecure_channel(GRPC_ADDR) as channel:
                stub = rssani_pb2_grpc.RssaniServiceStub(channel)
                stub.VerTimer(rssani_pb2.EmptyRequest())
            return
        except grpc.RpcError:
            time.sleep(0.2)
    raise RuntimeError("rssani did not start in time")


def tearDownModule():
    global PROC
    if PROC and PROC.poll() is None:
        try:
            with grpc.insecure_channel(GRPC_ADDR) as channel:
                stub = rssani_pb2_grpc.RssaniServiceStub(channel)
                stub.Shutdown(rssani_pb2.EmptyRequest())
            PROC.wait(timeout=5)
        except Exception:
            PROC.send_signal(signal.SIGTERM)
            PROC.wait(timeout=5)


class TestGrpc(unittest.TestCase):
    def setUp(self):
        self.channel = grpc.insecure_channel(GRPC_ADDR)
        self.stub = rssani_pb2_grpc.RssaniServiceStub(self.channel)

    def tearDown(self):
        self.channel.close()

    # --- Read-only methods ---

    def test_ver_ultimo(self):
        response = self.stub.VerUltimo(rssani_pb2.EmptyRequest())
        self.assertIsInstance(response.value, str)
        # Should contain a date-like string (dd/MM/yyyy hh:mm:ss)
        self.assertRegex(response.value, r"\d{2}/\d{2}/\d{4} \d{2}:\d{2}:\d{2}")

    def test_ver_timer(self):
        response = self.stub.VerTimer(rssani_pb2.EmptyRequest())
        self.assertIsInstance(response.value, int)
        self.assertGreater(response.value, 0)

    def test_ver_log(self):
        response = self.stub.VerLog(rssani_pb2.LogRequest(ini=0, fin=0))
        self.assertIsInstance(response.lines, (list, type(response.lines)))

    def test_lista_expresiones_empty(self):
        response = self.stub.ListaExpresiones(rssani_pb2.EmptyRequest())
        self.assertEqual(len(response.entries), 0)

    def test_lista_auths_empty(self):
        response = self.stub.ListaAuths(rssani_pb2.EmptyRequest())
        self.assertEqual(len(response.entries), 0)

    def test_ver_opciones(self):
        response = self.stub.VerOpciones(rssani_pb2.EmptyRequest())
        self.assertIsInstance(response.fromMail, str)
        self.assertIsInstance(response.toMail, str)
        self.assertIsInstance(response.path, str)

    # --- Regexp CRUD ---

    def test_regexp_crud(self):
        # Add
        add_resp = self.stub.AnadirRegexp(rssani_pb2.AnadirRegexpRequest(
            nombre="test.*pattern", fecha="31-12-2030", mail=False, tracker="", dias=0
        ))
        self.assertTrue(add_resp.value)

        regexps = self.stub.ListaExpresiones(rssani_pb2.EmptyRequest())
        names = [r.nombre for r in regexps.entries]
        self.assertIn("test.*pattern", names)
        idx = names.index("test.*pattern")

        # Edit by index
        edit_resp = self.stub.EditarRegexpI(rssani_pb2.EditarRegexpIRequest(
            regexpOrig=idx, regexpDest="edited.*pattern"
        ))
        self.assertFalse(edit_resp.value)
        regexps = self.stub.ListaExpresiones(rssani_pb2.EmptyRequest())
        self.assertEqual(regexps.entries[idx].nombre, "edited.*pattern")

        # Edit by name
        edit_resp = self.stub.EditarRegexp(rssani_pb2.EditarRegexpRequest(
            regexpOrig="edited.*pattern", regexpDest="final.*pattern"
        ))
        self.assertFalse(edit_resp.value)
        regexps = self.stub.ListaExpresiones(rssani_pb2.EmptyRequest())
        self.assertEqual(regexps.entries[idx].nombre, "final.*pattern")

        # Toggle active
        before = regexps.entries[idx].activa
        activ_resp = self.stub.ActivarRegexp(rssani_pb2.ActivarRegexpRequest(
            regexpOrig=idx
        ))
        self.assertFalse(activ_resp.value)
        regexps = self.stub.ListaExpresiones(rssani_pb2.EmptyRequest())
        after = regexps.entries[idx].activa
        self.assertNotEqual(before, after)

        # Delete by index
        count_before = len(regexps.entries)
        self.stub.BorrarRegexpI(rssani_pb2.BorrarRegexpIRequest(pos=idx))
        regexps = self.stub.ListaExpresiones(rssani_pb2.EmptyRequest())
        count_after = len(regexps.entries)
        self.assertEqual(count_after, count_before - 1)

    def test_regexp_add_and_delete_by_name(self):
        self.stub.AnadirRegexp(rssani_pb2.AnadirRegexpRequest(
            nombre="deleteme", fecha="", mail=False, tracker="", dias=0
        ))
        self.stub.BorrarRegexpS(rssani_pb2.BorrarRegexpSRequest(nombre="deleteme"))
        regexps = self.stub.ListaExpresiones(rssani_pb2.EmptyRequest())
        names = [r.nombre for r in regexps.entries]
        self.assertNotIn("deleteme", names)

    def test_regexp_move(self):
        self.stub.AnadirRegexp(rssani_pb2.AnadirRegexpRequest(
            nombre="move_a", fecha="", mail=False, tracker="", dias=0
        ))
        self.stub.AnadirRegexp(rssani_pb2.AnadirRegexpRequest(
            nombre="move_b", fecha="", mail=False, tracker="", dias=0
        ))
        regexps = self.stub.ListaExpresiones(rssani_pb2.EmptyRequest())
        names = [r.nombre for r in regexps.entries]
        idx_a = names.index("move_a")
        idx_b = names.index("move_b")

        self.stub.MoverRegexp(rssani_pb2.MoverRegexpRequest(from_position=idx_a, to=idx_b))
        regexps = self.stub.ListaExpresiones(rssani_pb2.EmptyRequest())
        self.assertEqual(regexps.entries[idx_b].nombre, "move_a")

        # Cleanup
        for name in ("move_a", "move_b"):
            self.stub.BorrarRegexpS(rssani_pb2.BorrarRegexpSRequest(nombre=name))

    # --- Auth CRUD ---

    def test_auth_crud(self):
        add_resp = self.stub.AnadirAuth(rssani_pb2.AnadirAuthRequest(
            tracker="https://test.tracker", uid="uid1", password="pass1", passkey="key1"
        ))
        self.assertTrue(add_resp.value)

        auths = self.stub.ListaAuths(rssani_pb2.EmptyRequest())
        trackers = [a.tracker for a in auths.entries]
        self.assertIn("https://test.tracker", trackers)

        self.stub.BorrarAuth(rssani_pb2.BorrarAuthRequest(tracker="https://test.tracker"))
        auths = self.stub.ListaAuths(rssani_pb2.EmptyRequest())
        trackers = [a.tracker for a in auths.entries]
        self.assertNotIn("https://test.tracker", trackers)

    # --- Options ---

    def test_poner_opciones(self):
        resp = self.stub.PonerOpciones(rssani_pb2.PonerOpcionesRequest(
            fromMail="from@test.com", toMail="to@test.com", path="/tmp/test"
        ))
        self.assertTrue(resp.value)
        opts = self.stub.VerOpciones(rssani_pb2.EmptyRequest())
        self.assertEqual(opts.fromMail, "from@test.com")
        self.assertEqual(opts.toMail, "to@test.com")
        self.assertEqual(opts.path, "/tmp/test")

    def test_cambia_timer(self):
        resp = self.stub.CambiaTimer(rssani_pb2.CambiaTimerRequest(tiempo=5))
        self.assertTrue(resp.value)

    def test_poner_credenciales(self):
        resp = self.stub.PonerCredenciales(rssani_pb2.PonerCredencialesRequest(
            user="newuser", password="newpass"
        ))
        self.assertTrue(resp.value)

    # --- Save ---

    def test_guardar(self):
        resp = self.stub.Guardar(rssani_pb2.EmptyRequest())
        self.assertTrue(resp.value)


if __name__ == "__main__":
    unittest.main(verbosity=2)
